### ISSUE TITLE
add installation guide in Readme

### ISSUE THREAD

**Issue by jeevikasirwani** [Irtiza751/fomogram#120]

**Comment by Irtiza751** [comment]
https://github.com/Irtiza751/fomogram/blob/Issue-120/documentation/README.md

**Comment by Irtiza751** [comment]
Let me know if you need anything else

**Comment by jeevikasirwani** [comment]
![image](https://github.com/Irtiza751/fomogram/assets/83456541/afaf97a5-999b-4539-ac1b-962a30c32f89)
maybe the steps don't appear on public page

**Comment by Irtiza751** [comment]
Try switching main branch to issue-120/documentation
